### ISSUE TITLE
Diaboloid

### ISSUE THREAD

**Issue by zxv497** [oasys-kit/OASYS-SYNED#6]
After the update, there is no widget component called Diaboloid. I run the example called oasys_workspace_diaboloid.ows which is found in github.
The system givens an error message as UnknownWidgetDefinition('orangecontrib.syned.widgets.tools.ow_diaboloid.OWDiaboloid').

**Comment by srio** [comment]
That's very weird!

1) Could you show me your options->add-ons page:
![image](https://user-images.githubusercontent.com/502315/169763307-2592b9e1-5931-4cce-8d06-fd92a3904eaa.png)


2) Could you send me all the log (with error included)

3) Which platform are you using? (I'll send you more debugging commands depending on it)

**Comment by zxv497** [comment]
1. ![image](https://user-images.githubusercontent.com/55216756/170859740-34b50b68-2b89-4f86-8b56-09f9162aa8e8.png)
2. I don't konw where the log is. After finding it, I will send you it.
3. win10

**Comment by zxv497** [comment]
XOPPY.
![image](https://user-images.githubusercontent.com/55216756/171793583-92ff92d0-4bfd-4348-80d7-eb471a8b0c49.png)
![image](https://user-images.githubusercontent.com/55216756/171793596-9514edba-c8a0-43e8-85af-97e93d5ca710.png)
![image](https://user-images.githubusercontent.com/55216756/171793623-8378779d-c77c-4e47-b4c2-15d8e6c9ce13.png)
![image](https://user-images.githubusercontent.com/55216756/171793804-a01eb98b-3441-4ab2-b006-ea1242c0748d.png)

**Comment by zxv497** [comment]
ShadowOui 
![image](https://user-images.githubusercontent.com/55216756/171794825-8f7907df-09a1-4853-aa36-b959fd12c8fd.png)
![image](https://user-images.githubusercontent.com/55216756/171794889-c6576341-a6e1-48b9-a89e-10419d863fcf.png)
![image](https://user-images.githubusercontent.com/55216756/171794935-e0270fec-51f1-4f3d-ae5a-b272fe3368e8.png)

**Comment by zxv497** [comment]
This is issue.
![image](https://user-images.githubusercontent.com/55216756/171795666-21dcb354-4869-4948-870c-37a5d83aecb4.png)

**Comment by srio** [comment]
There is a problem with the conda environment. Your Oasys is using your anaconda installation in ```D:ProgramData\Anaconda3```. Oasys use a private miniconda that must be installed in your home directory ```C:\users\maiowu\miniconda3```. I recommend to reinstall from scratch Oasys following the instructions in  https://github.com/oasys-kit/oasys-installation-scripts/wiki/Install-Oasys-in-Windows-10 
Please let me know the result.

**Comment by zxv497** [comment]
![image](https://user-images.githubusercontent.com/55216756/171875695-38521f39-cb35-46cf-bfc0-68d2202255a6.png)
![image](https://user-images.githubusercontent.com/55216756/171875853-16fd11f4-b5db-43fe-bf6a-81216b27a2d8.png)
 The situation is correct?

**Comment by zxv497** [comment]
I reinstall from scratch Oasys following the instructions. But Oasys don't appear. 
![image](https://user-images.githubusercontent.com/55216756/171983323-32dab451-ca1a-4615-8a5d-626e835ea791.png)
 I do following the picture. 
![image](https://user-images.githubusercontent.com/55216756/171983413-5f23370f-f9ef-4159-b4bc-67ffa14f0cf8.png)
result:
![image](https://user-images.githubusercontent.com/55216756/171983492-9fd9378c-f999-4a85-999a-bf9b80351d13.png)

**Comment by srio** [comment]
Does it work now? (try to start Oasys using ```python -m oasys.canvas```)


If not, delete your c:\Users\maiowu\Miniconda3 and try to install it by hand. Download miniconda3 fom ```https://repo.continuum.io/miniconda/Miniconda3-py37_4.8.2-Windows-x86_64.exe``` and install it in your $HOME\Miniconda

Then, in a cmd activate miniconda3 using ```c:\Users\maiowu\Miniconda3\Scripts\Activate``` and enter:

```
pip install pip --upgrade
pip install setuptools --upgrade

conda install git
conda install -c conda-forge xraylib=3.3.0
pip install oasys1 --upgrade

pip install numba --upgrade
pip uninstall -y oasys-srwpy
pip install oasys-srwpy --upgrade
pip install PyQtWebEngine==5.15.2 --upgrade

python -m oasys.canvas -l4
```
